# All the info generated by the game is populated into this hash, and read at
# different times to determine a particular result.
$game_stats = {
  :living_room_visits => 0,
  :kitchen_visits => 0,
  :bathroom_visits => 0,
  :bedroom_visits => 0,
  :basement_visits => 0,
  :garage_visits => 0,
  :total_room_visits => 0,
  :has_item => "empty"
}
# This is something I found on StackOverflow that creates a "press any key to
# continue" interaction with the player.
require 'io/console'
def continue
  puts "
>>"
  STDIN.getch
end
# Any time the player has to enter a number for a choice, their input goes through
# this function to ensure that it's valid. If not, the user is prompted to try
# entering their choice again.
def input_filter(name, input, acceptable_inputs, choices)
  if acceptable_inputs.include?(input) == true
    $game_stats[:"#{name}"] = input
  else
    sleep 1
    puts "
Seriously! #{$game_stats[:name]} WHAT SHOULD WE DO???"
    sleep 1
    puts "
    #{choices}
    "
    new_input = gets.chomp.to_i
    if acceptable_inputs.include?(new_input) == true
      $game_stats[:"#{name}"] = new_input
    else
      sleep 1
      puts "
OMG I guess I'll just deal with the spider myself. Have a nice life!
 "
      exit!
    end
  end
end
# This determines what room the spider will be found in, based on the character
# length of the name entered at the beginning of the game.
def spider_locator

  if $game_stats[:name].size <= 5
    $game_stats[:over5] = false
  else
    $game_stats[:over5] = true
  end

  if $game_stats[:name].size % 3 == 0
    $game_stats[:threemainder] = 0
  elsif $game_stats[:name].size % 3 == 1
    $game_stats[:threemainder] = 1
  else
    $game_stats[:threemainder] = 2
  end

  if $game_stats[:threemainder] == 0 && $game_stats[:over5] == false
    $game_stats[:spider_location] = "living room"
  elsif $game_stats[:threemainder] == 0 && $game_stats[:over5] == true
      $game_stats[:spider_location] = "kitchen"
  elsif $game_stats[:threemainder] == 1 && $game_stats[:over5] == false
      $game_stats[:spider_location] = "bathroom"
  elsif $game_stats[:threemainder] == 1 && $game_stats[:over5] == true
      $game_stats[:spider_location] = "bedroom"
  elsif $game_stats[:threemainder] == 2 && $game_stats[:over5] == false
      $game_stats[:spider_location] = "basement"
  elsif $game_stats[:threemainder] == 2 && $game_stats[:over5] == true
      $game_stats[:spider_location] = "garage"
  else
    $game_stats[:spider_location] = "garage"
  end
end
# This method initiates the method for a specific room, based on user input.
def room_sender(room_num)
  if room_num == 1
    living_room
  elsif room_num == 2
    kitchen
  elsif room_num == 3
    bathroom
  elsif room_num == 4
    bedroom
  elsif room_num == 5
    basement
  else
    garage
  end
  sleep 1
end
# This handles the logic when the user decides to pick up an item, leave it behind,
# or swap it for a different one.
def get_item(item, choice)
  sleep 1
  if $game_stats[:has_item] != "empty" && choice == 1
    puts "
You pick up the #{item} and return the #{$game_stats[:has_item]} to where you
found it."
    $game_stats[:has_item] = "#{item}"
  elsif choice == 1
    puts "
Great. We now have a #{item}."
    $game_stats[:has_item] = "#{item}"
  else
    puts "
Cool, yeah what would we do with a dumb old #{item} anyway?"
  end
end
# The end of the game. Initiated when the player enters the room where the spider is.
def spider_faceoff
  puts "
AIEEEEEEEEEEEE!!!!!!!!!!!!!!!!!!!!!
 "
  sleep 0.5
  puts "   |       |"
  puts "   \\   _   /"
  puts " \\  \\/###\\/  /"
  puts "  \\__|###|__/"
  puts "  ___|###|___"
  puts " /  /\\###/\\  \\ "
  puts "/  /  |O|  \\  \\ "
  puts "  |         |
    "

  continue
  puts "
You stand in horror as the grotesque, hairy creature slowly decends from the
#{$game_stats[:current_room]} ceiling above you.
  "
  continue
# If you're unlucky enough to stumble upon the spider before picking up any item,
# this horrible death awaits you.
  if $game_stats[:has_item] == "empty"
    puts "
You remain paralyzed in abject terror as the spider lands right on top
of your head.
"
    continue
    puts "
Slowly, it cralws down over your left eye.
"
    continue
    puts "
You both see and feel it sinking its two fangs into your pupil.
"
    continue
    puts "
You both see and feel the venom pumping into your eye.
"
    continue
    puts "
Eventually the poison diffuses throughout your body until it reaches your heart.
"
    continue
    puts "
You die standing right there, your face frozen in an eerie mask of dread.
"
    continue
    puts "
GAME OVER
 "
# If you have an item, you choose to use it or not.
  elsif $game_stats[:has_item] != "empty"
    puts "
Suddenly you remember the #{$game_stats[:has_item].upcase}. Do you use it on the spider?
"
    continue
    options = "
Enter 1 to use the #{$game_stats[:has_item]}.
Otherwise enter 2.
"
    puts options
    choice = gets.chomp.to_i
    input_filter("faceoff", choice, [1, 2], options)
# Choosing to face the spider without your item results in a quick end.
    if choice == 2
      puts "
Facing the spider empty-handed was a bad idea. It bites you and you die.

GAME OVER
 "
    elsif $game_stats[:faceoff] == 1
# These are all the different endings based on the item you're using and the
# original objective (catch/kill/avoid) that you chose at the beginning.
      if $game_stats[:objective] == 1 && $game_stats[:has_item] == "cup"
    puts "
You start to sweat as the beastly arachnid floats down to the floor and begins
to walk in circles. Realizing the spider isn't focused on attacking you, you are
able to put your fear aside and gently corral the spider into the cup. You
notice the spider seems to be disoriented and slightly panicked.
"
    continue
    puts "
As you carry it outside to set it free, you briefly make eye contact with about
3 or 4 of the spider's eyes. In that moment, you establish a deep connection
with this often-maligned, widely-misunderstood ...scared, vulnerable little
creature. \"Aw, heck,\" you think, \"this little buddy is just as afraid as I am.
Aren't we all looking for the same thing in this topsy-turvy ride called life?
We could use a little more peace, love and understanding.\"
"
    continue
    puts "
\"Yeah...\"
"
    continue
    puts "
Your thought trails off as you find yourself standing at the edge of the
backyard, at the precipice of a tearful goodbye with your newfound friend.
Inhaling deeply, you release the spider and hold in the swelling emotions until
you can run back inside and lock yourself in the bedroom, where you sob
uncontrollably and cry a whole bunch of tears.
"
    continue
    puts "
The next day you're an emotional wreck. For weeks you are heartbroken, but with
the help of concerned friends and family members, you're finally able to put the
loss of the only creature that's ever truly KNOWN you aside and get back to the
business of living life.
"
    continue
    puts "
Then, on a rather ordinary day several months later, you open your back door to
something completely unexpected. You find your spider friend on the stoop,
waiting to greet you. The spider has returned to you! The joy you feel in that
moment instantly makes all the pain you've been experiencing melt away. Reaching
down, you extend a hand for your friend of friends to climb upon. You turn and
go back into the house. Together.
"
    continue
    puts "
Life takes on a beautiful rhythm. Days of cheerful companionship roll into weeks
of wonder, which accumulate into mirthful months, ultimately entering your
scrapbooks as the cherished years of yesterday. You convert the #{$game_stats[:spider_location]},
the place where the two of you first met, into a web-strewn spider's palace for
the new housemate. You also come up with a name for your cherished spider, and
it's perfect: #{$game_stats[:name]} Junior. EVERYTHING is perfect, in fact.
Just right.
"
    continue
    puts "
Then one morning, you open the door to the #{$game_stats[:spider_location]} to
find your dearest friend looking slightly shriveled. #{$game_stats[:name]} Jr. is
dying! Fighting back the tears, you say goodbye, one last time.
"
    continue
    puts "
Devastated though you are, you know the time you had together was a gift. You
take comfort in knowing there are no regrets. After posting your thoughts and
feelings on social media, several mainstream news sites start to pick up your
story and you go viral as HELL. As interest and demand snowballs all over the
world, you write a memoir to tell your story, exactly how it happened, once and
for all. \"LOVE: What I Learned from #{$game_stats[:name]} Junior\" is the first
book to ever sell a billion copies.
"
    continue
    puts "
People all over the world are so moved by your story, and they vow to open their
own hearts to the world's arachnids. A new age begins as the two species begin to
cooperate ...and to co-evolve. War, poverty, and buzzkills in general are
eradicated from human nature as we learn the virtues of spiderhood. As the
millenia stretch on, higher forms of life - life that exists beyond the scope of
our imagination - begin to emerge from the historic partnership.
"
    continue
    puts "
The world is saved!
"
    continue
    puts "
And even though you're much too modest to admit it, it's all because you and
#{$game_stats[:name]} Junior made a choice one day to say YES.
"
    continue
    puts "
Yes to each other. Yes to love.
"
    sleep 1
    puts "
THE END"
      elsif $game_stats[:objective] == 1 && $game_stats[:has_item] == "jar"
        puts "
You quickly unscrew the lid to the jar and hold the open vessel directly under
the spider. You can barely believe it as the arachnid drops right to the
bottom of the jar.
"
        continue
        puts "
Quick, the lid!
"
        continue
        puts "
You look proudly upon your new pet and decide to name it #{$game_stats[:name]} Junior.
"
        continue
        puts "
You poke some air holes in the lid and throw a handful of grass in the jar,
hoping that it helps to make the spider feel at home.
"
        continue
        puts "
The excitement for your new pet eventually wears off, and you return to the
ordinary comings and goings of daily life.
"
        continue
        puts "
One day you catch a glimpse of the jar over on the window sill, and notice that
#{$game_stats[:name]} Junior has dried to a crisp. You realize that you had
neglected to provide it with a source of water.
"
        continue
        puts "
\"Ope!\"
"
        continue
        puts "
But hey, congrats on catching that thing! You survived the ordeal, although it
ended up being kind of a bummer for the spider.
"
        sleep 3
        puts "
THE END
 "
      elsif $game_stats[:objective] == 1 && $game_stats[:has_item] == "shovel"
        puts "
Ok, let's try to catch the spider with this shovel.
"
        continue
        puts "
You hold out the shovel for the spider to land on. It lands on the blade, runs
across the handle, and bites your hand, injecting deadly venom into your
bloodstream.
"
        continue
        puts "
You're dead before you hit the floor.
"
        sleep 1
        puts "
THE END
 "
      elsif $game_stats[:objective] == 1 && $game_stats[:has_item] == "book"
        puts "
I guess we can try to catch the spider with our book...
"
        continue
        puts "
You hold the book out for the spider to land on. With lighning speed, it runs
across the book, onto your hand, up your arm, onto your face, into your gaping
mouth, and lodges itself in your windpipe, causing you to choke to death.
"
        continue
        puts "
The spider survives and lays a bunch of eggs in your mouth. The hatchlings feast
on your body, growing to the size of dachshunds.
"
        sleep 4
        puts "
GAME OVER
 "
      elsif $game_stats[:objective] == 1 && $game_stats[:has_item] == "blanket"
        puts "
The spider lands on the floor and starts moving toward you.
"
        continue
        puts "
In an attempt to capture the advancing arachnid, you throw the blanket over it.
"
        continue
        puts "
Nothing happens for a while. The blanket is just sitting in the middle of the
#{$game_stats[:current_room]} floor. You scoop it up, hoping that the spider is
in there somewhere. You run outside with it.
"
        continue
        puts "
You set the blanket on the ground, put on some protective gloves, and carefully
start to unfurl it, one fold at a time.
"
        continue
        puts "
You never find the spider.
"
        continue
        puts "
You rush back to the #{$game_stats[:current_room]}. It isn't in there. You scour
the entire house over. No spider.
"
        continue
        puts "
You are now doomed to live the rest of your life never knowing where the spider
went, or if it's hiding around the next corner, or if it's waiting for its chance
to strike, or if you'll ever be able to have another moment that isn't
overshadowed by fear.
"
        continue
        puts "
GAME OVER
 "
      elsif $game_stats[:objective] == 1 && $game_stats[:has_item] == "raincoat"
        puts "
Sure, let's catch a spider with a raincoat.
"
        continue
        puts "
You throw the raincoat onto the #{$game_stats[:current_room]} floor under the
spider. It lands on it!
"
        continue
        puts "
You grab the other end of the coat and drag it behind you. You start
running toward the front door. While running, you turn to look and see the
spider sitting in place on the coat, seemingly content with getting a free ride.
You smile.
"
        continue
        puts "
You turn your head back just in time to run face-first into a wall.
"
        continue
        puts "
The blow knocks you out and you fall backward onto the spider, crushing it into
goo and leaving you with two black eyes, a bloody nose, bruised ribs and a
raincoat that you'll never wear again.
"
        continue
        puts "
You survive the ordeal, but there are no winners today.
"
        continue
        puts "
GAME OVER
 "

      elsif $game_stats[:objective] == 2 && $game_stats[:has_item] == "cup"
        puts "
You throw the cup at the spider.
"
        continue
        puts "
WIFF!
"
        continue
        puts "
The cup misses and shatters against the #{$game_stats[:current_room]} wall.
"
        continue
        puts "
The spider is alarmed by all the commotion, and goes into attack mode. It cuts
loose from its web line and drops onto your head!
"
        continue
        puts "
You scream and frantically beat at your ears, hair and face. The spider runs
down the back of your head and into your shirt. It quickly finds a tender spot
to sink its fangs in, and that's the end of #{$game_stats[:name]}.
"
        continue
        puts "
THE END
 "
      elsif $game_stats[:objective] == 2 && $game_stats[:has_item] == "jar"
        puts "
You throw the jar at the spider.
"
        continue
        puts "
WIFF!
"
        continue
        puts "
The jar misses and shatters against the #{$game_stats[:current_room]} wall.
"
        continue
        puts "
The spider is alarmed by all the commotion, and goes into attack mode. It cuts
loose from its web line and drops onto your head!
"
        continue
        puts "
You scream and frantically beat at your ears, hair and face. The spider runs
down the back of your head and into your shirt. It quickly finds a tender spot
to sink its fangs in, and that's the end of #{$game_stats[:name]}.
"
        continue
        puts "
THE END
 "
      elsif $game_stats[:objective] == 2 && $game_stats[:has_item] == "shovel"
        puts "
All RIGHT! We've been waiting for this chance!
"
        continue
        puts "
You swing the shovel, smacking the spider out of the air like you're playing
teeball. It flies across the #{$game_stats[:current_room]}, into a wall, lands
on the floor and lays motionless, other than a couple of twitching legs.
"
        continue
        puts "
As you look down at the broken creature, you suddenly feel a pang of guilt. But
it's too late to do anything now. Then you remember your friend down the
street who's studying to be a spider surgeon.
"
        continue
        puts "
You call her and explain the situation, asking if there is anything she can do to
help mend the spider and give it another chance at life. Alas, you had
misunderstood.
"
        continue
        puts "
Turns out she's studying to be a PEOPLE surgeon, not a SPIDER surgeon. And
spider surgery isn't even a thing!
"
        continue
        puts "
The spider dies.
"
        continue
        puts "
Right then and there, you resolve to redeem yourself from this horrible act. You
commit yourself to developing the field of Spider Surgery so that other spiders
can be saved.
"
        continue
        puts "
You work nonstop to make your goal a reality, working 3 jobs to pay for school
so that you can learn everything about spiders and invent new techniques for
doing surgery on them.
"
        continue
        puts "
Your research catches on in the academic world as universities look to add Spider
Surgery to their catalog of Non-Practical Studies. As the originator of all the
foundational knowledge, you become quite wealthy and famous from book royalties
and speaking engagements.
"
        continue
        puts "
You realize your life has changed for the better. You think about the tens of
spiders that have been saved as a result of your research, and eventually come
to forgive yourself for killing that spider you found in the #{$game_stats[:current_room]}
all those years ago.
"
        continue
        puts "
You get to be rich AND guilt-free. Way to go!
"
        sleep 2
        puts "
THE END
 "
      elsif $game_stats[:objective] == 2 && $game_stats[:has_item] == "book"
        puts "
Yes, this book will be excellent for killing the spider...
"
        continue
        puts "
You take a moment to breathe a sigh of relief and congratulate yourself on
selecting a weapon that can successfully defeat your eight-legged enemy. Moving
the book from one hand to the other, you appreciate its size and weight, noting
that there is even a dust jacket that can be removed once it's been used to
crush the spider, so your hardcover edition won't get all gross with bug guts.
"
        continue
        puts "
\"The perfect spider killer!\"
"
        continue
        puts "
\"spider... killer...\"
"
        continue
        puts "
\"Spider...\"
"
        continue
        puts "
OMG!
"
        continue
        puts "
You were so lost in your own thoughts of self-congratulation that you forgot
about actually KILLING the REAL SPIDER! You look up from the book just in time
to see it hanging right in front of your face, with long, spindly legs
reaching out for you and fangs primed to sink into the tip of your nose.
"
        continue
        puts "
You instinctively raise your arms to protect your face, accidentally throwing
the book across the #{$game_stats[:current_room]} in the process. You lunge for
it as the spider cuts loose, dropping to the floor by your feet. It starts
running along your prone body, right toward your head.
"
        continue
        puts "
You crawl across the floor, desperately reaching for the book.
"
        continue
        puts "
Almost there...
"
        continue
        puts "
The spider is past your waist and advancing rapidly!
"
        continue
        puts "
Your outstretched fingertips can just... barely... touch the edge of the book...
"
        continue
        puts "
The spider leaps at your face, spreading its legs in the air like the fiendish
hand about to grab you by the head.
"
        continue
        puts "
You get the book!
"
        continue
        puts "
In one motion, you turn and throw the hardcover novel with impeccable accuracy.
The book catches the spider in mid-flight, slams into a wall, and falls several
feet, crashing onto a small table.
"
        continue
        puts "
Slowly, you begin to lift yourself off the floor into a sitting position. You
look like hell, but thanks to the adrenaline pumping through your system, you
feel quite calm and level-headed.
"
        continue
        puts "
\"Feel pretty COOL, actually!\" you think as you pull a pack of cigarettes
from your pocket and let one dangle from your relaxed lip.
"
        continue
        puts "
You're just about to light up when you hear the book hit the floor behind you...
"
        continue
        puts "
You quickly spin around and sweep your eyes over the room. The book is now
laying open on the floor. There is a dent in the drywall where it hit. But no
spider.
"
        continue
        puts "
Quickly and quietly, you glide over to the book and pick it up. There are no guts
on the dust cover, but there does appear to be a slight indentation from where
the spider was caught between book and wall.
"
        continue
        puts "
\"Holy hell, this is one tough customer!\"
"
        continue
        puts "
As you inspect the back of the book, you start to read the description. You've
never actually READ Gravity's Rainbow, even though you know you really SHOULD,
but you don't even know what it's ABOUT, and it's so damn LONG, you'd
really have to plan for it, set aside some time...
"
        continue
        puts "
\"Aw crud, I did it again!\"
"
        continue
        puts "
Sure enough, you look up just in time to see the spider launch at your head from
the opposite wall.
"
        continue
        puts "
\"Let's dance, bug breath!\"
"
        continue
        puts "
You backflip out of the spider's flight path, use your lighter to set the book
on fire, and hurl it at the airborne aggressor with all your strength.
"
        continue
        puts "
The flaming book catches the spider in midair and crashes through the #{$game_stats[:current_room]}
window. As the spider plunges 287 stories to the sidewalk below, you pull your
uzi machine gun out from inside your boot, run toward the window at full speed,
and dive through the ragged glass frame.
"
        continue
        puts "
With perfect form, you plummet head-first toward the street until you're below
the falling, flaming spider, which is also badly crushed and full of glass
shards. You turn to shoot up at your enemy, spraying it with a hail of bullets
that rip through its body and pull strings of spider goo out the other side.
"
        continue
        puts "
You land on an inflatable pink gorilla that's promoting the annual Toyotathon
Savings Event at the local car dealership. It cushions your fall as you plunge
into it, and then springs you back out and onto your feet. Not bad!
"
        continue
        puts "
Meanwhile, the spider and flaming book scream down to oblivion as they crash
into a large gasoline tanker truck and create an explosion that can be seen from
space.
"
        continue
        puts "
You finally get to light your cigarette, which never left your lip, on the
burning wreckage. Your super-hot significant other runs to your side and showers
you with kisses.
"
        continue
        puts "
\"Sorry I was late for dinner, babe. I just couldn't put my book down.\"
"
        continue
        puts "
The scene fades to black and credits roll as Aerosmith performs a hard rock
version of \"The Itsy Bitsy Spider\".
"
        sleep 2
        puts "
THE END
 "
      elsif $game_stats[:objective] == 2 && $game_stats[:has_item] == "blanket"
        puts "
Oh, sure. Let's kill the spider with a BLANKET.
"
        continue
        puts "
Like THAT'S gonna work!
"
        continue
        puts "
What are you gonna like, tuck it in all cozy?
  "
        continue
        puts "
Read it a bedtime stowwy?
"
        continue
        puts "
Sing it a widdle wuwwabye untiw it gwoes to sweep?
"
        continue
        puts "
PSHHHHH!
"
        continue
        puts "
Naw. The spider bites you, and you die.
"
        sleep 1
        puts "
GAME OVER
"
        continue
        puts "
We'll make sure to bury you with your little blanket so you don't get too cold
in your coffin! HAHAHAHAHAHA
 "
      elsif $game_stats[:objective] == 2 && $game_stats[:has_item] == "raincoat"
        puts "
Ok, try to hit the spider with it!
"
        continue
        puts "
You swing the raincoat at the dangling foe. THWAP! It collides with the spider
but doesn't really do any damage.
"
        continue
        puts "
And now you don't know where it went.
"
        continue
        puts "
You hold the raincoat open to look for where the spider might be hiding.
"
        continue
        puts "
It crawls out of a sleeve and bites your hand.
"
        continue
        puts "
\"Ow!\"
"
        continue
        puts "
The spider gets away and your hand becomes infected. Gross!
"
        sleep 1
        puts "
GAME OVER
 "

      elsif $game_stats[:objective] == 3 && $game_stats[:has_item] == "cup"
        puts "
Not really sure how we're going to use a cup avoid a spider, but sure, go
ahead and try!
"
        continue
        puts "
As the spider begins to descend from above, you stare intensely at the
glass cup.
"
        continue
        puts "
The spider lands on your head.
"
        continue
        puts "
You note the thickness of the glass.
"
        continue
        puts "
The spider rears its head back and unsheathes its long, pointed fangs.
"
        continue
        puts "
You watch the glare of reflected light as it plays upon the cup's surface.
"
        continue
        puts "
The spider sinks its fangs into your scalp and injects you with deadly, corrosive
venom.
"
        continue
        puts "
You observe the way the glass bends light as you look through it.
"
        continue
        puts "
Your hair falls out and your flesh begins to decompose in a growing circle
radiating outward from the bite wound.
"
        continue
        puts "
You remove the cup from in front of your eyes, but your view of the #{$game_stats[:current_room]}
remains blurry and distorted. It is the last thing you see before you die.
"
        continue
        puts "
GAME OVER
 "
      elsif $game_stats[:objective] == 3 && $game_stats[:has_item] == "jar"
        puts "
Not really sure how we're going to use a jar avoid a spider, but sure, you go
ahead and try!
"
        continue
        puts "
As the spider begins to descend from above, you stare intensely at the
glass jar.
"
        continue
        puts "
The spider lands on your head.
"
        continue
        puts "
You note the thickness of the glass.
"
        continue
        puts "
The spider rears its head back and unsheathes its long, pointed fangs.
"
        continue
        puts "
You watch the glare of reflected light as it plays upon the jar's surface.
"
        continue
        puts "
The spider plunges its fangs into your scalp and injects you with deadly, corrosive
venom.
"
        continue
        puts "
You observe the way the glass bends the light as you look through it.
"
        continue
        puts "
Your hair falls out and your flesh begins to decompose in a growing circle
radiating outward from the bite wound.
"
        continue
        puts "
You remove the jar from in front of your eyes, but your view of the #{$game_stats[:current_room]}
remains blurry and distorted. It is the last thing you see before you die.
"
        continue
        puts "
GAME OVER
 "
      elsif $game_stats[:objective] == 3 && $game_stats[:has_item] == "shovel"
        puts "
\"Look, a shovel!\" you yell as you throw it across the room.
"
        continue
        puts "
The spider turns to watch as the shovel flies by and crashes through the
#{$game_stats[:current_rooom]} window.
"
        continue
        puts "
It turns back to you, dangling just millimeters from your face. The distraction
has failed!
"
        continue
        puts "
You know what happens next, right?
"
        continue
        puts "
BITES FACE YOU DIE!
"
        sleep 2
        puts "
GAME OVER!!!!
 "
      elsif $game_stats[:objective] == 3 && $game_stats[:has_item] == "book"
        puts "
You quickly open the book, turn to the first page and escape into the world of
imagination.
"
        continue
        puts "
As you come to know each character and setting in the book, you become a part of
the story, living through each scene in the plot with stunning clarity. You build
a whole new life apart from the one you once had.
"
        continue
        puts "
And then one day, you drop dead. Because in real life, you got bit by a
poisonous spider.
"
        continue
        puts "
Impressive speed-reading skills, though!
"
        sleep 1
        puts "
GAME OVER
 "
      elsif $game_stats[:objective] == 3 && $game_stats[:has_item] == "blanket"
        puts "
You think fast and drape the blanket over your head and shoulders.
"
        continue
        puts "
The spider lands on top of it and crawls harmlessly down to the floor.
"
        continue
        puts "
The spider walks right out the #{$game_stats[:current_room]} doorway and turns the corner,
never to be seen again.
"
        continue
        puts "
You have succeeded in avoiding the spider. Admittedly, it's not the most exciting
outcome, but you did what you set out to do, technically \"winning\" the game.
  "
        continue
        puts "
So THAT's pretty neat!
"
        continue
        puts "
And I decided to do something really special for you.
  "
        continue
        puts "
Are you ready?
"
        continue
        puts "
Here it is:
"
        sleep 1
        puts "
--------------------------------
      *~* Spider Game *~*
             #{$game_stats[:name].upcase}
          ^ ^ ^ ^ ^ ^
        official winner
--------------------------------
"
        sleep 4
        puts "
Please print this certificate for your records.
"
        continue
        puts "
Thanks for playing!

THE END
 "
      elsif $game_stats[:objective] == 3 && $game_stats[:has_item] == "raincoat"
        puts "
You quickly put on the raincoat and pull the hood over your head.
"
        continue
        puts "
The spider lands on top of it and crawls harmlessly down to the floor.
"
        continue
        puts "
The spider walks right out the #{$game_stats[:current_room]} doorway and turns the corner,
never to be seen again.
"
        continue
        puts "
You have succeeded in avoiding the spider. Admittedly, it's not the most exciting
outcome, but you did what you set out to do, technically \"winning\" the game.
  "
        continue
        puts "
So THAT's pretty neat!
"
        continue
        puts "
And I decided to do something extra special for you.
  "
        continue
        puts "
Are you ready?
"
        continue
        puts "
Here it is:
"
        sleep 1
        puts "
--------------------------------
      *~* Spider Game *~*
             #{$game_stats[:name].upcase}
          ^ ^ ^ ^ ^ ^
        official winner
--------------------------------
"
        sleep 4
        puts "
Please print this certificate for your records.
"
        continue
        puts "
Thanks for playing!

THE END
 "
else puts "This should not happen. Please tell Mark if it does!"
      end
    end
  end
  exit!
end
# There is a function for each room that determines different outcomes based on
# whether the user has been there before, and if the spider is in there. Each
# room also presents one item that the user may choose to take.
def living_room
  $game_stats[:living_room_visits] += 1
  $game_stats[:total_room_visits] += 1
  $game_stats[:current_room] = "living room"
  puts "
Sure, let's go to the living room...
    "
  continue
  if $game_stats[:current_room] == $game_stats[:spider_location]
    spider_faceoff
  elsif $game_stats[:living_room_visits] > 1
    puts "
The living room is just as we left it.
"
    continue
    if $game_stats[:has_item] != "blanket"
      puts "
That BLANKET is still over there if you want it!
"
      continue
      puts "
Do you want to pick up the blanket? Enter 1 for YES or 2 for NO.
"
      $game_stats[:take_item] = gets.chomp.to_i
      input_filter("take_item", $game_stats[:take_item], [1, 2], "
Enter 1 for YES, I want the BLANKET, or 2 for NO, I DO NOT want the dang BLANKET!
      ")

      get_item("blanket", $game_stats[:take_item])
    else
    end
  else
    puts "
You don't see anything unusual upon entering, so you plop your butt down on the
couch. Looking around, you notice a television set, some 'Live-Laugh-Love'
styled word art, and a very classy sectional sofa with built-in cup holders on
the armrests.
"
    continue
    puts "
You also notice a neatly-folded blanket hanging over the back of one chair.
Should we take it?
"
    continue
    puts "
Enter 1 to take the blanket, or 2 to leave it here.
"
    $game_stats[:take_item] = gets.chomp.to_i
    input_filter("take_item", $game_stats[:take_item], [1, 2], "
Enter 1 for YES, I want the BLANKET, or 2 for NO, I DO NOT want the dang BLANKET!
    ")
    get_item("blanket", $game_stats[:take_item])
  end
  continue
  puts "
Welp! I think we've seen enough of the living room. Where should we go next?"
  sleep 1
  options = "
Enter 2 to go to the KITCHEN.
Enter 3 to go to the BATHROOM.
Enter 4 to go to the BEDROOM.
Enter 5 to go to the BASEMENT.
Enter 6 to go to the GARAGE.
"
  puts options

  $game_stats[:room] = gets.chomp.to_i

  input_filter("room", $game_stats[:room], [2, 3, 4, 5, 6], options)

  room_sender($game_stats[:room])
end

def kitchen

  $game_stats[:kitchen_visits] += 1
  $game_stats[:total_room_visits] += 1
  $game_stats[:current_room] = "kitchen"
  puts "
Sure, let's go to the kitchen...
"
  continue

  if $game_stats[:current_room] == $game_stats[:spider_location]
    spider_faceoff
  elsif $game_stats[:kitchen_visits] > 1
    puts "
Here we are again. Are you still hungry or something?
"
    continue

    if $game_stats[:has_item] != "cup"
      puts "
That CUP is still over on the table...
"
      continue
      puts "
Do you want to grab it? Enter 1 for YES or 2 for NO.
"
      $game_stats[:take_item] = gets.chomp.to_i
      input_filter("take_item", $game_stats[:take_item], [1, 2], "
Enter 1 for YES, I want the CUP, or 2 for NO, I DO NOT want the dang CUP!
      ")

      get_item("cup", $game_stats[:take_item])
    else
    end
  else
    puts "
You step into the kitchen and look around. No spider in sight, so you mosey on
over to the fridge and grab yourself a Go-Gurt.
"
    continue
    puts "
It's then that you notice an empty CUP on the kitchen table. It might come in
handy ...should we bring it with us?
"
    continue
    puts "
Enter 1 to bring the cup, or 2 to leave it here.
"
    $game_stats[:take_item] = gets.chomp.to_i
    input_filter("take_item", $game_stats[:take_item], [1, 2], "
Enter 1 for YES, I want the CUP, or 2 for NO, I DO NOT want the dang CUP!
    ")
    get_item("cup", $game_stats[:take_item])
  end
  continue

  puts "
Well, I think we've seen enough of this room. Where should we go next?"
  sleep 1
  options = "
Enter 1 to go to the LIVING ROOM.
Enter 3 to go to the BATHROOM.
Enter 4 to go to the BEDROOM.
Enter 5 to go to the BASEMENT.
Enter 6 to go to the GARAGE.
"
  puts options

  $game_stats[:room] = gets.chomp.to_i

  input_filter("room", $game_stats[:room], [1, 3, 4, 5, 6], options)

  room_sender($game_stats[:room])
end

def bathroom

  $game_stats[:bathroom_visits] += 1
  $game_stats[:total_room_visits] += 1
  $game_stats[:current_room] = "bathroom"
  puts "
Let's investigate the bathroom...
"
  continue
  if $game_stats[:current_room] == $game_stats[:spider_location]
    spider_faceoff
  elsif $game_stats[:bathroom_visits] > 1
    puts "
Yep, looks like the bathroom. Nothing new here!
"
    continue
    if $game_stats[:has_item] != "jar"
      puts "
That JAR is still on the counter.
"
      continue
      puts "
Do you want to pick up the jar? Enter 1 for YES or 2 for NO.
"
      $game_stats[:take_item] = gets.chomp.to_i
      input_filter("take_item", $game_stats[:take_item], [1, 2], "
Enter 1 for YES, I want the JAR, or 2 for NO, I DO NOT want the dang JAR!
      ")

      get_item("jar", $game_stats[:take_item])
    else
    end
  else
    puts "
The ol' water closet is a floofy affair, wallpapered with an old-timey flower
motif and packed with a multitude of cocker spaniel art: framed paintings and
photos, cross-stitch, and glass figurines. There's even a special shrine devoted
to Arthur, famous dog to none other than Sir Elton John.
"
    continue
    puts "
You also notice a cluster of cotton balls contained tastefully in a pink glass
JAR. It could be useful later ...should we bring it?
"
    continue
    puts "
Enter 1 to take the jar, or 2 to leave it here.
"
    $game_stats[:take_item] = gets.chomp.to_i
    input_filter("take_item", $game_stats[:take_item], [1, 2], "
Enter 1 for YES, I want the JAR, or 2 for NO, I DO NOT want the dang ol' JAR!!!!!
    ")
    get_item("jar", $game_stats[:take_item])
  end
  continue
  puts "
It's kind of crowded in here. Can we go somewhere else?"
  sleep 1
  options = "
Enter 1 to go to the LIVING ROOM.
Enter 2 to go to the KITCHEN.
Enter 4 to go to the BEDROOM.
Enter 5 to go to the BASEMENT.
Enter 6 to go to the GARAGE.
"
  puts options

  $game_stats[:room] = gets.chomp.to_i

  input_filter("room", $game_stats[:room], [1, 2, 4, 5, 6], options)

  room_sender($game_stats[:room])
end

def bedroom

  $game_stats[:bedroom_visits] += 1
  $game_stats[:total_room_visits] += 1
  $game_stats[:current_room] = "bedroom"
  puts "
Ok, we can go to the bedroom ...but don't get any ideas!
"
  continue
  if $game_stats[:current_room] == $game_stats[:spider_location]
    spider_faceoff
  elsif $game_stats[:bedroom_visits] > 1
    puts "
Well, here we are in the bedroom again. Why do you keep bringing me back here, hmmmmm??
"
    continue
    if $game_stats[:has_item] != "raincoat"
      puts "
That RAINCOAT is still hanging in the closet.
"
      continue
      puts "
Do you want to put on the RAINCOAT? Enter 1 for YES or 2 for NO.
"
      $game_stats[:take_item] = gets.chomp.to_i
      input_filter("take_item", $game_stats[:take_item], [1, 2], "
Enter 1 for YES, I want the RAINCOAT, or 2 for NO, I DO NOT want the dang RAINCOAT!
      ")

      get_item("raincoat", $game_stats[:take_item])
    else
    end
  else
    puts "
Just as you would expect, there is a bed in this room. Hence it's a BEDROOM.
Get it, BED? ROOM?? Oh nevermind. You humans have no concept of string
concatenation.
"
    continue
    puts "
Oh, but look there's also a closet! And there's a RAINCOAT hanging in there.
Should we take it with us?
    "
    continue
    puts "
Enter 1 to take the raincoat, or 2 to leave it here.
"
    $game_stats[:take_item] = gets.chomp.to_i
    input_filter("take_item", $game_stats[:take_item], [1, 2], "
Enter 1 for YES, I want the RAINCOAT, or 2 for NO, I DO NOT want the dang RAINCOAT!!!!!
    ")
    get_item("raincoat", $game_stats[:take_item])
  end

  continue
  puts "
Well, to be honest I feel a little awkward just sitting with you here in the
bedroom. No offense. Can we go somewhere else?"
  sleep 2
  options = "
Enter 1 to go to the LIVING ROOM.
Enter 2 to go to the KITCHEN.
Enter 3 to go to the BATHROOM.
Enter 5 to go to the BASEMENT.
Enter 6 to go to the GARAGE.
"
  puts options

  $game_stats[:room] = gets.chomp.to_i

  input_filter("room", $game_stats[:room], [1, 2, 3, 5, 6], options)

  room_sender($game_stats[:room])
end

def basement

    $game_stats[:basement_visits] += 1
    $game_stats[:total_room_visits] += 1
    $game_stats[:current_room] = "basement"
    puts "
I guess we can check out the basement. Hopefully it's not too creepy down there!
"
    continue
    if $game_stats[:current_room] == $game_stats[:spider_location]
      spider_faceoff
    elsif $game_stats[:basement_visits] > 1
      puts "
Oh yeah, that's right. The basement is actually a very pleasant living space!
"
      continue
      if $game_stats[:has_item] != "book"
        puts "
That BOOK is still on the shelf over there.
"
        continue
        puts "
Did you want to grab that? Enter 1 for YES or 2 for NO.
"
        $game_stats[:take_item] = gets.chomp.to_i
        input_filter("take_item", $game_stats[:take_item], [1, 2], "
Enter 1 for YES, I want the BOOK, or 2 for NO, I DO NOT want the dang BOOK!!!!!!!!
        ")

        get_item("book", $game_stats[:take_item])
      else
      end
    else
      puts "
Your fears of a dark, dingy, concrete confines are swiftly assuaged as you step
into the fully finished - and actually quite cozy - basement living space.
Complete with carpet, a papason chair, and decorative musical instruments on the
walls, this would be a great place to sit and read one of the many books from the
shelf.
"
    continue
    puts "
There's a particularly hefty BOOK titled 'Gravity's Rainbow' on the shelf. Do we
take it with us?
"
      continue
      puts "
Enter 1 to get the book, or 2 to leave it here.
"
      $game_stats[:take_item] = gets.chomp.to_i
      input_filter("take_item", $game_stats[:take_item], [1, 2], "
Enter 1 for YES, I want the BOOK, or 2 for NO, I DO NOT want the dang BOOK!!!!!
      ")
      get_item("book", $game_stats[:take_item])
    end

    continue
    puts "
So that's the basement. Where ya wanna go now?"
    sleep 1
    options = "
Enter 1 to go to the LIVING ROOM.
Enter 2 to go to the KITCHEN.
Enter 3 to go to the BATHROOM.
Enter 4 to go to the BEDROOM.
Enter 6 to go to the GARAGE.
"
    puts options

    $game_stats[:room] = gets.chomp.to_i

    input_filter("room", $game_stats[:room], [1, 2, 3, 4, 6], options)

    room_sender($game_stats[:room])
end

def garage

  $game_stats[:garage_visits] += 1
  $game_stats[:total_room_visits] += 1
  $game_stats[:current_room] = "garage"
  puts "
To the garage we go!
"
  continue
  if $game_stats[:current_room] == $game_stats[:spider_location]
    spider_faceoff
  elsif $game_stats[:garage_visits] > 1
    puts "
Once again, we re-enter the previously visited garage that we have already been
to. Why are we here?
"
    continue
    if $game_stats[:has_item] != "shovel"
      puts "
There's that SHOVEL. Is that what we came for?
"
      continue
      puts "
Enter 1 to GRAB the shovel, or 2 to LEAVE IT HERE.
"
      $game_stats[:take_item] = gets.chomp.to_i
      input_filter("take_item", $game_stats[:take_item], [1, 2], "
Enter 1 for YES, I want the SHOVEL, or 2 for NO, I DO NOT WANT THE DANG SHOVEL!!!!!!!!
      ")

      get_item("shovel", $game_stats[:take_item])
    else
    end
  else
    puts "
Cold, poorly lit, and littered with random crap, the garage is about what
you'd expect. No spiders to be seen, though. You survey the piles of expired
coupons, barrels of empty Red Bull cans, and stacks of Rob Schneider comedies on
VHS.
"
    continue
    puts "
You also happen to spot some yard tools in the corner, including a nice big
SHOVEL ...should we take that with us?
"
    continue
    puts "
Enter 1 to take the shovel, or 2 to leave it here.
"
    $game_stats[:take_item] = gets.chomp.to_i
    input_filter("take_item", $game_stats[:take_item], [1, 2], "
Enter 1 for YES, I want the SHOVEL, or 2 for NO, I DO NOT want the dang SHOVEL!!!!!
        ")
        get_item("shovel", $game_stats[:take_item])
  end
  continue

  puts "
Can we leave the garage now? I'm cold."
  sleep 1
  options = "
Enter 1 to go to the LIVING ROOM.
Enter 2 to go to the KITCHEN.
Enter 3 to go to the BATHROOM.
Enter 4 to go to the BEDROOM.
Enter 5 to go to the BASEMENT.
"
  puts options

  $game_stats[:room] = gets.chomp.to_i

  input_filter("room", $game_stats[:room], [1, 2, 3, 4, 5], options)

  room_sender($game_stats[:room])
end

################### GAME START ####################
print "
OH, NO! There's a POISONOUS SPIDER in the house!!!!!
 "
sleep 1
puts "
 :0
"
sleep 1
puts " :(

 "
sleep 1
puts "(PRO TIP: Press any key to continue when you see the \">>\" symbol!)"
continue
puts "
What should we do about the spider???"
sleep 1
options = "
Enter 1 if we should CATCH it.
Enter 2 if we should KILL it.
Enter 3 if we should AVOID it at all costs.
"
puts options

choice = gets.chomp.to_i

input_filter("objective", choice, [1, 2, 3], options)
sleep 1
puts "
Good idea! Hey, what's your name, by the way?
"

$game_stats[:name] = gets.chomp
spider_locator

sleep 1
puts "
Well don't worry #{$game_stats[:name]}, we'll get through this together!
"
# sleep 3
continue
puts "
So, where in the house should we go?
"
sleep 1
options = "
Enter 1 to go to the LIVING ROOM.
Enter 2 to go to the KITCHEN.
Enter 3 to go to the BATHROOM.
Enter 4 to go to the BEDROOM.
Enter 5 to go to the BASEMENT.
Enter 6 to go to the GARAGE.
"
puts options

$game_stats[:room] = gets.chomp.to_i

input_filter("room", $game_stats[:room], [1, 2, 3, 4, 5, 6], options)

room_sender($game_stats[:room])
